# Generated by Django 5.2.17 on 2026-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_channel',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('whatsapp', 'WhatsApp Arrangement')], default='paystack', max_length=20),
        ),
    ]
