# Generated by Django 5.2.17 on 2026-09-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_deliveryzone_rename_shipping_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('paystack', 'Pay Online'), ('whatsapp', 'Order via WhatsApp')], default='paystack', max_length=20),
        ),
    ]
