# Generated by Django 5.2.17 on 2026-09-21 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_order_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=120)),
                ('city_area', models.CharField(max_length=150)),
                ('landmark', models.CharField(blank=True, max_length=180)),
                ('delivery_type', models.CharField(choices=[('fixed', 'Fixed Delivery Fee'), ('quote', 'Delivery Fee To Be Confirmed')], default='fixed', max_length=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_zone',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.deliverylocation'),
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
    ]
